<?php


 function autoload_9c0bf30d7c8fc1d6820217bbe8a3fef5($class)
{
    $classes = array(
        'PttAVM\Service' => __DIR__ .'/Service.php',
        'PttAVM\ArrayOfint' => __DIR__ .'/ArrayOfint.php',
        'PttAVM\ArrayOfstring' => __DIR__ .'/ArrayOfstring.php',
        'PttAVM\Tedarikci' => __DIR__ .'/Tedarikci.php',
        'PttAVM\ArrayOfStokKontrolDetay' => __DIR__ .'/ArrayOfStokKontrolDetay.php',
        'PttAVM\StokKontrolDetay' => __DIR__ .'/StokKontrolDetay.php',
        'PttAVM\KayitDurum' => __DIR__ .'/KayitDurum.php',
        'PttAVM\ArrayOfUrunResim' => __DIR__ .'/ArrayOfUrunResim.php',
        'PttAVM\UrunResim' => __DIR__ .'/UrunResim.php',
        'PttAVM\ArrayOfVariants' => __DIR__ .'/ArrayOfVariants.php',
        'PttAVM\Variants' => __DIR__ .'/Variants.php',
        'PttAVM\ArrayOfKategoriDetay' => __DIR__ .'/ArrayOfKategoriDetay.php',
        'PttAVM\KategoriDetay' => __DIR__ .'/KategoriDetay.php',
        'PttAVM\ArrayOfAltKategoriDetay' => __DIR__ .'/ArrayOfAltKategoriDetay.php',
        'PttAVM\AltKategoriDetay' => __DIR__ .'/AltKategoriDetay.php',
        'PttAVM\ArrayOfKargoBilgi' => __DIR__ .'/ArrayOfKargoBilgi.php',
        'PttAVM\KargoBilgi' => __DIR__ .'/KargoBilgi.php',
        'PttAVM\ArrayOfTedarikciSiparisKontrol' => __DIR__ .'/ArrayOfTedarikciSiparisKontrol.php',
        'PttAVM\TedarikciSiparisKontrol' => __DIR__ .'/TedarikciSiparisKontrol.php',
        'PttAVM\ArrayOfTedarikciSiparisKontrolV2' => __DIR__ .'/ArrayOfTedarikciSiparisKontrolV2.php',
        'PttAVM\TedarikciSiparisKontrolV2' => __DIR__ .'/TedarikciSiparisKontrolV2.php',
        'PttAVM\ArrayOfSiparisUrun' => __DIR__ .'/ArrayOfSiparisUrun.php',
        'PttAVM\SiparisUrun' => __DIR__ .'/SiparisUrun.php',
        'PttAVM\ArrayOfclsResultTransferObject' => __DIR__ .'/ArrayOfclsResultTransferObject.php',
        'PttAVM\clsResultTransferObject' => __DIR__ .'/clsResultTransferObject.php',
        'PttAVM\ArrayOfStokUrun' => __DIR__ .'/ArrayOfStokUrun.php',
        'PttAVM\StokUrun' => __DIR__ .'/StokUrun.php',
        'PttAVM\ArrayOfUrunResimBase64' => __DIR__ .'/ArrayOfUrunResimBase64.php',
        'PttAVM\UrunResimBase64' => __DIR__ .'/UrunResimBase64.php',
        'PttAVM\ArrayOfVariant' => __DIR__ .'/ArrayOfVariant.php',
        'PttAVM\Variant' => __DIR__ .'/Variant.php',
        'PttAVM\ArrayOfVariantAttr' => __DIR__ .'/ArrayOfVariantAttr.php',
        'PttAVM\VariantAttr' => __DIR__ .'/VariantAttr.php',
        'PttAVM\ArrayOfVariantCombination' => __DIR__ .'/ArrayOfVariantCombination.php',
        'PttAVM\VariantCombination' => __DIR__ .'/VariantCombination.php',
        'PttAVM\StokResult' => __DIR__ .'/StokResult.php',
        'PttAVM\AktifUrunRequest' => __DIR__ .'/AktifUrunRequest.php',
        'PttAVM\ApiResult' => __DIR__ .'/ApiResult.php',
        'PttAVM\categoryMainResponse' => __DIR__ .'/categoryMainResponse.php',
        'PttAVM\ArrayOfcategory' => __DIR__ .'/ArrayOfcategory.php',
        'PttAVM\category' => __DIR__ .'/category.php',
        'PttAVM\error' => __DIR__ .'/error.php',
        'PttAVM\categoryResponse' => __DIR__ .'/categoryResponse.php',
        'PttAVM\category_detail' => __DIR__ .'/category_detail.php',
        'PttAVM\categoryResponseTree' => __DIR__ .'/categoryResponseTree.php',
        'PttAVM\ArrayOfCategory' => __DIR__ .'/ArrayOfCategory.php',
        'PttAVM\Category' => __DIR__ .'/Category.php',
        'PttAVM\ServiceStateResult' => __DIR__ .'/ServiceStateResult.php',
        'PttAVM\KullaniciTedarikciBilgisiGetir' => __DIR__ .'/KullaniciTedarikciBilgisiGetir.php',
        'PttAVM\KullaniciTedarikciBilgisiGetirResponse' => __DIR__ .'/KullaniciTedarikciBilgisiGetirResponse.php',
        'PttAVM\StokKontrolListesi' => __DIR__ .'/StokKontrolListesi.php',
        'PttAVM\StokKontrolListesiResponse' => __DIR__ .'/StokKontrolListesiResponse.php',
        'PttAVM\BarkodKontrol' => __DIR__ .'/BarkodKontrol.php',
        'PttAVM\BarkodKontrolResponse' => __DIR__ .'/BarkodKontrolResponse.php',
        'PttAVM\KategoriListesi' => __DIR__ .'/KategoriListesi.php',
        'PttAVM\KategoriListesiResponse' => __DIR__ .'/KategoriListesiResponse.php',
        'PttAVM\AltKategoriListesi' => __DIR__ .'/AltKategoriListesi.php',
        'PttAVM\AltKategoriListesiResponse' => __DIR__ .'/AltKategoriListesiResponse.php',
        'PttAVM\KargoBilgiListesi' => __DIR__ .'/KargoBilgiListesi.php',
        'PttAVM\KargoBilgiListesiResponse' => __DIR__ .'/KargoBilgiListesiResponse.php',
        'PttAVM\StokGuncelle' => __DIR__ .'/StokGuncelle.php',
        'PttAVM\StokGuncelleResponse' => __DIR__ .'/StokGuncelleResponse.php',
        'PttAVM\StokFiyatGuncelle' => __DIR__ .'/StokFiyatGuncelle.php',
        'PttAVM\StokFiyatGuncelleResponse' => __DIR__ .'/StokFiyatGuncelleResponse.php',
        'PttAVM\StokFiyatGuncelle2' => __DIR__ .'/StokFiyatGuncelle2.php',
        'PttAVM\StokFiyatGuncelle2Response' => __DIR__ .'/StokFiyatGuncelle2Response.php',
        'PttAVM\SiparisKontrolListesi' => __DIR__ .'/SiparisKontrolListesi.php',
        'PttAVM\SiparisKontrolListesiResponse' => __DIR__ .'/SiparisKontrolListesiResponse.php',
        'PttAVM\TedarikciAltKategoriListesi' => __DIR__ .'/TedarikciAltKategoriListesi.php',
        'PttAVM\TedarikciAltKategoriListesiResponse' => __DIR__ .'/TedarikciAltKategoriListesiResponse.php',
        'PttAVM\GetVersion' => __DIR__ .'/GetVersion.php',
        'PttAVM\GetVersionResponse' => __DIR__ .'/GetVersionResponse.php',
        'PttAVM\SiparisKontrolListesiV2' => __DIR__ .'/SiparisKontrolListesiV2.php',
        'PttAVM\SiparisKontrolListesiV2Response' => __DIR__ .'/SiparisKontrolListesiV2Response.php',
        'PttAVM\OlmayanUrunAdetleriSifirla' => __DIR__ .'/OlmayanUrunAdetleriSifirla.php',
        'PttAVM\OlmayanUrunAdetleriSifirlaResponse' => __DIR__ .'/OlmayanUrunAdetleriSifirlaResponse.php',
        'PttAVM\StokGuncelleBulk' => __DIR__ .'/StokGuncelleBulk.php',
        'PttAVM\StokGuncelleBulkResponse' => __DIR__ .'/StokGuncelleBulkResponse.php',
        'PttAVM\StokGuncelleV2Bulk' => __DIR__ .'/StokGuncelleV2Bulk.php',
        'PttAVM\StokGuncelleV2BulkResponse' => __DIR__ .'/StokGuncelleV2BulkResponse.php',
        'PttAVM\StokFiyatGuncelleBulk' => __DIR__ .'/StokFiyatGuncelleBulk.php',
        'PttAVM\StokFiyatGuncelleBulkResponse' => __DIR__ .'/StokFiyatGuncelleBulkResponse.php',
        'PttAVM\BarkodKontrolBulk' => __DIR__ .'/BarkodKontrolBulk.php',
        'PttAVM\BarkodKontrolBulkResponse' => __DIR__ .'/BarkodKontrolBulkResponse.php',
        'PttAVM\StokFiyatGuncelle3' => __DIR__ .'/StokFiyatGuncelle3.php',
        'PttAVM\StokFiyatGuncelle3Response' => __DIR__ .'/StokFiyatGuncelle3Response.php',
        'PttAVM\StokGuncelleV2' => __DIR__ .'/StokGuncelleV2.php',
        'PttAVM\StokGuncelleV2Response' => __DIR__ .'/StokGuncelleV2Response.php',
        'PttAVM\AktifYap' => __DIR__ .'/AktifYap.php',
        'PttAVM\AktifYapResponse' => __DIR__ .'/AktifYapResponse.php',
        'PttAVM\ServiceState' => __DIR__ .'/ServiceState.php',
        'PttAVM\ServiceStateResponse' => __DIR__ .'/ServiceStateResponse.php',
        'PttAVM\StokGuncelleTestApi' => __DIR__ .'/StokGuncelleTestApi.php',
        'PttAVM\StokGuncelleTestApiResponse' => __DIR__ .'/StokGuncelleTestApiResponse.php',
        'PttAVM\GetMainCategories' => __DIR__ .'/GetMainCategories.php',
        'PttAVM\GetMainCategoriesResponse' => __DIR__ .'/GetMainCategoriesResponse.php',
        'PttAVM\GetCategory' => __DIR__ .'/GetCategory.php',
        'PttAVM\GetCategoryResponse' => __DIR__ .'/GetCategoryResponse.php',
        'PttAVM\GetCategoryTree' => __DIR__ .'/GetCategoryTree.php',
        'PttAVM\GetCategoryTreeResponse' => __DIR__ .'/GetCategoryTreeResponse.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_9c0bf30d7c8fc1d6820217bbe8a3fef5');

// Do nothing. The rest is just leftovers from the code generation.
{
}
